services:
  neo4j:
    image: neo4j:4.0.3
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/streams
      NEO4J_dbms_logs_debug_level: DEBUG

  recommendation:
    build: ./recommendation-api
    command: python manage.py runserver 0.0.0.0:8025
    volumes:
      - .:/recommendation-api/code
    ports:
      - "8025:8025"

  kinopoisk:
    build: ./kinopoisk-api
    command: python manage.py runserver 0.0.0.0:8030
    volumes:
      - .:/kinopoisk-api/code
    ports:
      - "8030:8030"