server:
  port: 9000

spring:
  application:
    name: Backend

  neo4j:
    uri: bolt://neo4j:7687
    authentication:
      username: neo4j
      password: streams

logging:
  level:
    org:
      springframework:
        data:
          neo4j: DEBUG